version: '3.8'

services:
    dashboard_app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - VITE_API_URL=${VITE_API_URL}
        networks:
            - umubyeyi_shared_network
    # If you need to connect to a backend service on the host machine (development)
    # extra_hosts:
    #  - "host.docker.internal:host-gateway"

networks:
    umubyeyi_shared_network:
        external: true

