version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umubyeyi-elevate-dashboard
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    # If you need to connect to a backend service on the host machine (development)
    # extra_hosts:
    #  - "host.docker.internal:host-gateway"
